version: '3.8'

services:
  # Backend .NET
  buildtruck-backend:
    build: .
    container_name: buildtruck-dotnet
    ports:
      - "5000:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=buildtruck;user=root;password=BuildTruck123!
      - TokenSettings__SecretKey=4f8a2c1e9b7d3f6a8c5e2b9f1a4d7c0e3b6f9a2c5e8b1f4a7d0c3f6b9e2a5d8c1f
      - EmailSettings__SmtpPassword=hjkj kqmw pigk utwz
      - CloudinarySettings__ApiSecret=wLNbBt2imcpgflwDdOsr3CoHZPI
    networks:
      - buildtruck-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: buildtruck-mysql
    environment:
      MYSQL_ROOT_PASSWORD: BuildTruck123!
      MYSQL_DATABASE: buildtruck
      MYSQL_USER: buildtruckuser
      MYSQL_PASSWORD: BuildTruck123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - buildtruck-network

volumes:
  mysql_data:

networks:
  buildtruck-network:
    driver: bridge